spring:
  application:
    name: ClientesBeneficio
  jpa:
    database: h2
    show-sql: false
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
      continue-on-error: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
files:
  sk: "https://raw.githubusercontent.com/SistemasComoHogar/ClientesBack/main/Referencias/sk_formato.json"
  th: "https://raw.githubusercontent.com/SistemasComoHogar/ClientesBack/main/Referencias/th_formato.xml"
server:
  port: 8001
